### ISSUE TITLE
🐛 Bug -  type declaration not found in generated sdk

### ISSUE THREAD

**Issue by adharshchottu** [contentful/template-blog-webapp-nextjs#102]
# Bug report

## Summary

when generating the `sdk.ts` using `yarn graphql-codegen:generate`, Cannot find module 'graphql-request/dist/types.dom' or its corresponding type declarations.ts(2307) error in `sdk.ts:2`

## Environment

node version: 18.17.0
yarn version: 1.22.19

## Steps to reproduce

`yarn graphql-codegen:generate`

## Expected results

working SDK

## Actual results

error in `sdk.ts` file. Cannot find module 'graphql-request/dist/types.dom' or its corresponding type declarations.ts(2307)

**Comment by mahouhou** [comment]
I have this same issue, I tried updating and also downgrading graphql-request, or commenting out the line. I now can't run the codegen script to update types for new queries. I'm not sure what's triggered this bug. It was fine until today (after several weeks of development) when I added a new query and installed the React Fontawesome package. If I undo my changes however, the bug remains.

**Comment by denkristoffer** [comment]
Hey 👋 I believe this issue was due to the version of graphql-codegen we were using. We upgraded multiple packages a few months back and it should have fixed this problem, but please let us know if the problem persists.

**Comment by adharshchottu** [comment]
después de algunos ajustes de versión, todo funciona bien.
