### ISSUE TITLE
💬 Feedback - Please clarify automatic content updates on Netlify

### ISSUE THREAD

**Issue by dstr89** [contentful/template-blog-webapp-nextjs#174]
Hey, this template is working really great for me. I deployed my app to Netlify, got great Lighthouse scores, and the content changes I published in Contentful became visible live in minutes.

I have a question regarding this last part, as I do not fully understand how it works. I was expecting that I need to add some webhook that triggers a build on Netlify on a content change in Contentful. However, this seems to be working OOTB using the template. 

Can you please tell me how this works and where is it set up? I assume that Netlify hosts static HTML created in the build process and that any content change requires a new build. How did you solve this? Does every content change rebuild the complete project or only the affected pages?

BR,
Daniel

**Comment by cf-remylenoir** [comment]
Hi Daniel,

We are thrilled your experience with the template is positive.

Before explaining further the content changes publishing I would like to know if you kept the default template [Content Preview](https://www.contentful.com/developers/docs/tutorials/general/content-preview/) configuration (pointing to https://blog.templates.contentful.com) or if you added yours, pointing to your deployed Netlify URL?

**Comment by dstr89** [comment]
Hi Remy,

for now I kept the default settings as I was interested more in the end
user experience.

Best regards,
Daniel Strmečki

**Comment by dstr89** [comment]
Hi @cf-remylenoir, 

I still don't understand how my content changes in Contentful are visible on the Netlify live site within seconds/minutes: https://contenful-strmecki.netlify.app/ without me adding any webhooks or seeing any builds in Netlify?

Can you please explain how did you solve this? I assume there is something OOTB doing the magic here. Does every content change rebuild the complete project or only the affected pages?

**Comment by dstr89** [comment]
Nevermind, I find an answer to my question, I see that the tutorial uses TTL-based invalidation of 60 sec.

BR,
Daniel
